In [70]:
import subprocess
import sys
import os

# Define a function to install packages
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# List of packages to install
packages = [
    "pandas",
    "numpy",
    "scikit-learn",
    "pickle-mixin",
    "pyarrow"
]

# Install each package
for package in packages:
    try:
        __import__(package)
    except ImportError:
        install(package)

#assign correct directory
name = sys.platform

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
import pickle
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor 
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import LinearSVC
import random as rm
from sklearn.metrics import classification_report, f1_score
import pickle as pk
from sklearn.preprocessing import PolynomialFeatures
from itertools import combinations
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Lasso
from sklearn.ensemble import IsolationForest
from sklearn.metrics import accuracy_score
from scipy.spatial.distance import mahalanobis

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: pickle-mixin in /opt/anaconda3/lib/python3.12/site-packages (1.0.2)

In [71]:
import pandas as pd

# 1. Load the Stata dataset
df1 = pd.read_stata("CMF/CMF_1880_SS1.dta")

In [72]:
# check if "hands_children" is in the columns
for col in df1.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "material" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "output" in col:
        print(col)
    if "product" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
product_total_value
material_kind1
material_qty1
material_kind_attr1
material_standardized_unit1
material_kind2
material_qty2
material_kind_attr2
material_standardized_unit2

In [73]:
# rename columns
df1.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
}, inplace=True)

In [74]:
df2 = pd.read_stata("CMF/CMF_1880_SS2.dta")
for col in df2.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "material" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "output" in col:
        print(col)
    if "product" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_superintendent
wage_machinist
wage_machine_tender
wage_rag_engineer
wage_foreman_loft
wage_foreman_fin
wage_skilled_other
wage_daily_unskilled
total_wages
material_total_value
product_total_value
material_kind1
material_qty1
material_kind_attr1
material_standardized_unit1
material_kind2
material_qty2
material_kind_attr2
material_standardized_unit2
material_kind3
material_qty3
material_kind_attr3
material_standardized_unit3
material_kind4
material_qty4
material_kind_attr4
material_standardized_unit4
material_kind5
material_qty5
material_kind_attr5
material_standardized_unit5
material_kind6
material_qty6
material_kind_attr6
material_standardized_unit6
material_kind7
material_qty7
material_kind_attr7
material_standardized_unit7
material_kind8
material_qty8
material_kind_attr8
material_standardized_unit8
material_kind9
material_qty9
material_kind_attr9
material_standardized_unit9

In [75]:
df2.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
}, inplace=True)

In [76]:
df3 = pd.read_stata("CMF/CMF_1880_SS3.dta")
for col in df3.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "material" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "output" in col:
        print(col)
    if "product" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
product_total_value
material_kind1
material_qty1
material_kind_attr1
material_standardized_unit1
material_kind2
material_qty2
material_kind_attr2
material_standardized_unit2
material_kind3
material_qty3
material_kind_attr3
material_standardized_unit3

In [77]:
df3.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
}, inplace=True)

In [78]:
df4 = pd.read_stata("CMF/CMF_1880_SS4.dta")
for col in df4.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "material" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "output" in col:
        print(col)
    if "prod" in col:
        print(col)
    if "total_value" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
tanning_mat_total_value
tanning_prod_leather
tanning_prod_skins
tanning_prod_total_value
tanning_prod_total_value
currying_mat_total_value
currying_prod_leather
currying_prod_skins
currying_prod_total_value
currying_prod_total_value
material_kind1
material_qty1
material_kind_attr1
material_standardized_unit1
material_kind2
material_qty2
material_kind_attr2
material_standardized_unit2
material_kind3
material_qty3
material_kind_attr3
material_standardized_unit3
material_kind4
material_qty4
material_kind_attr4
material_standardized_unit4
material_kind5
material_qty5
material_kind_attr5
material_standardized_unit5
material_kind6
material_qty6
material_kind_attr6
material_standardized_unit6
prod_kind1
prod_qty1
prod_kind_attr1
prod_unit1
prod_kind2
prod_qty2
prod_kind_attr2
prod_unit2
prod_kind3
prod_qty3
prod_kind_attr3
prod_unit3
prod_kind4
prod_qty4
prod_kind_attr4
prod_unit4

In [79]:
df4["materials_value"] = df4["tanning_mat_total_value"] + df4["currying_mat_total_value"]
df4["output"] = df4["tanning_prod_total_value"] + df4["currying_prod_total_value"]
df4["ind_broadest"] = df4["ind_broadest1"]

/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/2252699396.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df4["materials_value"] = df4["tanning_mat_total_value"] + df4["currying_mat_total_value"]
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/2252699396.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df4["output"] = df4["tanning_prod_total_value"] + df4["currying_prod_total_value"]
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/2252699396.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df4["ind_broadest"] = df4["ind_broadest1"]

In [80]:
df5 = pd.read_stata("CMF/CMF_1880_SS5.dta")
for col in df5.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "total_value" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "prod" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
sawmill_prod_lumber
sawmill_prod_laths
sawmill_prod_shingles
sawmill_prod_staves
sawmill_prod_headings
sawmill_prod_stock
sawmill_prod_total_value
sawmill_prod_total_value
sawmill_prod_value_other
remanuf_total_value
remanuf_workers
prod_kind1
prod_qty1
prod_kind_attr1
prod_unit1
prod_kind2
prod_qty2
prod_kind_attr2
prod_unit2
prod_kind3
prod_qty3
prod_kind_attr3
prod_unit3
prod_kind4
prod_qty4
prod_kind_attr4
prod_unit4
prod_kind5
prod_qty5
prod_kind_attr5
prod_unit5
prod_kind6
prod_qty6
prod_kind_attr6
prod_unit6

In [81]:
df5.rename(columns={
    "sawmill_prod_total_value": "output", 
    "material_total_value": "materials_value"
}, inplace=True)

In [82]:
df6 = pd.read_stata("CMF/CMF_1880_SS6.dta")
for col in df6.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "total_value" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "prod" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
prod_common_brick
prod_fire_brick
prod_pressed_brick
prod_tile_value
prod_drain_pipe_value
prod_value_other
product_total_value
product_total_value
prod_kind1
prod_qty1
prod_kind_attr1
prod_unit1
prod_kind2
prod_qty2
prod_kind_attr2
prod_unit2
prod_kind3
prod_qty3
prod_kind_attr3
prod_unit3
prod_kind4
prod_qty4
prod_kind_attr4
prod_unit4
prod_kind5
prod_qty5
prod_kind_attr5
prod_unit5

In [83]:
df6.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
    "ind_broadest1": "ind_broadest"
}, inplace=True)

In [84]:
df7 = pd.read_stata("CMF/CMF_1880_SS7.dta")
for col in df7.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "total_value" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "prod" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
prod_bbls_wheat
prod_bbls_rye_flour
prod_lbs_buckwheat_flour
prod_lbs_barley_meal
prod_lbs_corn_meal
prod_lbs_feed
prod_lbs_hominy
prod_value_other
product_total_value
product_total_value
prod_kind1
prod_qty1
prod_kind_attr1
prod_unit1
prod_kind2
prod_qty2
prod_kind_attr2
prod_unit2
prod_kind3
prod_qty3
prod_kind_attr3
prod_unit3
prod_kind4
prod_qty4
prod_kind_attr4
prod_unit4
prod_kind5
prod_qty5
prod_kind_attr5
prod_unit5
prod_kind6
prod_qty6
prod_kind_attr6
prod_unit6
prod_kind7
prod_qty7
prod_kind_attr7
prod_unit7

In [85]:
df7.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
}, inplace=True)

In [86]:
df8 = pd.read_stata("CMF/CMF_1880_SS8.dta")
for col in df8.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "cost" in col:
        print(col)
    if "worker" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_adult_female
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
milk_cost
cheese_cost
cheese_furnish_cost
butter_cost
butter_furnish_cost
cb_butter_cost
cb_cheese_cost
cb_butter_furnish_cost
cb_cheese_furnish_cost

In [87]:
df8["output"] = df8["butter_buttermilk_skim_value"] + df8["condensed_milk_value"]
df8["materials_value"] = df8["milk_cost"] + df8["cheese_cost"] + df8["cheese_furnish_cost"] + df8["butter_cost"] + df8["butter_furnish_cost"]

/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/2395739353.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df8["materials_value"] = df8["milk_cost"] + df8["cheese_cost"] + df8["cheese_furnish_cost"] + df8["butter_cost"] + df8["butter_furnish_cost"]

In [88]:
df9 = pd.read_stata("CMF/CMF_1880_SS9.dta")
for col in df9.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "total_value" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "prod" in col:
        print(col)
    if "female" in col:
        print(col)

file_name
firm_number
firm_name
capital
workers_max
workers_adult_male
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
prod_beef_fresh
prod_beef_canned
prod_beef_salted
prod_mutton_fresh
prod_pork_fresh
prod_pork_salted
prod_bacon_ham
prod_lard
prod_value_other
product_total_value
product_total_value
prod_kind1
prod_qty1
prod_kind_attr1
prod_unit1
prod_kind2
prod_qty2
prod_kind_attr2
prod_unit2
prod_kind3
prod_qty3
prod_kind_attr3
prod_unit3
prod_kind4
prod_qty4
prod_kind_attr4
prod_unit4
prod_kind5
prod_qty5
prod_kind_attr5
prod_unit5
prod_kind6
prod_qty6
prod_kind_attr6
prod_unit6
prod_kind7
prod_qty7
prod_kind_attr7
prod_unit7
prod_kind8
prod_qty8
prod_kind_attr8
prod_unit8

In [89]:
df9.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
}, inplace=True)

In [90]:
df12 = pd.read_stata("CMF/CMF_1880_SS12.dta")
for col in df12.columns:
    if "hands" in col: 
        print(col)
    if "capital" in col:
        print(col)
    if "file" in col:
        print(col)
    if "firm" in col:
        print(col)
    if "wage" in col:
        print(col)
    if "total_value" in col:
        print(col)
    if "worker" in col:
        print(col)
    if "prod" in col:
        print(col)
    if "female" in col:
        print(col)

file_name
firm_number
mat_total_value
prod_total_value
prod_total_value
firm_name
capital
workers_max
workers_adult_male
workers_children
wage_daily_skilled
wage_daily_unskilled
total_wages
material_total_value
prod_marketed
product_total_value
product_total_value
product_kind_clean
product_kind_attribute
product_enumerator_notes
product_misc
product_service
product_is_units
product_unsure
product_freq
product_comments
product_freq_two
file_name6
prod_kind1
prod_qty1

In [91]:
df12 = df12.rename(columns={
    "material_total_value": "materials_value",
    "product_total_value": "output",
})

In [92]:
dataframe = [df1, df2, df3, df4, df5, df6, df7, df8]

In [93]:
for col in df1.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df1[col] = pd.to_numeric(df1[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df1 = df1[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [94]:
df1.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_calhoun-benton_00114_L.jpg,1,Sinclair & Montgomery,3000.0,NaN,3.0,NaN,800.0,1800.0,4000.0,iron and steel products
1,AL_8_calhoun-benton_00115_L.jpg,1,Acker William,100.0,NaN,8.0,NaN,100.0,200.0,1000.0,iron and steel products
2,AL_8_calhoun-benton_00115_L.jpg,2,Paul Samuel,300.0,NaN,4.0,NaN,100.0,200.0,1000.0,iron and steel products
3,AL_8_calhoun-benton_00115_L.jpg,3,Martin Elijah,3500.0,NaN,7.0,NaN,130.0,130.0,500.0,iron and steel products
4,AL_8_calhoun-benton_00115_L.jpg,4,Martin William,350.0,NaN,7.0,NaN,150.0,130.0,500.0,iron and steel products

In [95]:
for col in df2.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df2[col] = pd.to_numeric(df2[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df2 = df2[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [96]:
df2.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_mobile_00673_L.jpg,1,Gal J.City Paper Co,125000.0,NaN,NaN,NaN,NaN,NaN,NaN,paper and printing
1,CA_8_marin_00280_L.jpg,1,Taylor Samuel P.,75000.0,NaN,25.0,1.0,12700.0,20000.0,45280.0,paper and printing
2,CA_8_san joaquin_00601_L.jpg,1,California Paper Co,300000.0,5.0,75.0,2.0,42722.0,138815.0,187774.0,paper and printing
3,CA_8_santa clara_00664_L.jpg,1,? Paper Mfg. Co.,150000.0,NaN,12.0,NaN,8000.0,NaN,45000.0,paper and printing
4,CA_8_santa clara_00664_L.jpg,2,? Brothers,5000.0,NaN,10.0,NaN,6500.0,NaN,16900.0,paper and printing

In [97]:
for col in df3.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df3[col] = pd.to_numeric(df3[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df3 = df3[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [98]:
df3.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_etowah_00353_L.jpg,1,Reeves Nathan,200.0,NaN,2.0,NaN,650.0,NaN,NaN,clothing and textiles
1,AL_8_etowah_00353_L.jpg,2,Gidley Jas,800.0,NaN,3.0,NaN,480.0,NaN,NaN,clothing and textiles
2,AL_8_etowah_00353_L.jpg,3,Schlburg Chas,1000.0,NaN,4.0,NaN,850.0,NaN,NaN,clothing and textiles
3,CA_8_san francisco_00481_L.jpg,1,S.W. Levy,150000.0,20.0,86.0,5.0,78800.0,121200.0,230000.0,clothing and textiles
4,CA_8_san francisco_00481_L.jpg,2,Buckingham & Hecht,380000.0,30.0,256.0,5.0,187000.0,345081.0,667668.0,clothing and textiles

In [99]:
for col in df4.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df4[col] = pd.to_numeric(df4[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

# Add any columns starting with "ind_"
ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df4 = df4[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [100]:
df4.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_barbour_00652_L.jpg,1,Stow & Hickey,8000.0,NaN,7.0,NaN,1200.0,60003120.0,80001000.0,leather products
1,AL_8_barbour_00653_L.jpg,1,Prier HWB & Co,1500.0,NaN,2.0,1.0,400.0,10001850.0,18003125.0,leather products
2,AL_8_bibb_00047_L.jpg,1,Davis J Madison,500.0,NaN,2.0,NaN,400.0,5001040.0,15001750.0,leather products
3,AL_8_blount_00052_L.jpg,1,Kael & Wods,1500.0,NaN,2.0,NaN,250.0,900535.0,8400900.0,leather products
4,AL_8_blount_00053_L.jpg,1,Daniel W Durban,1000.0,NaN,2.0,NaN,500.0,5001125.0,20001500.0,leather products

In [101]:
for col in df5.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
     df5[col] = pd.to_numeric(df5[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols 
df5 = df5[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [102]:
df5.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_autauga_00008_L.jpg,1,D. Pratt Gin Co.,6000.0,NaN,6.0,NaN,1500.0,3700.0,NaN,lumber
1,AL_8_autauga_00008_L.jpg,2,Scott Robt.,750.0,NaN,2.0,NaN,350.0,375.0,NaN,lumber
2,AL_8_autauga_00008_L.jpg,3,M.M Smith & Co,2500.0,NaN,10.0,1.0,2500.0,5000.0,NaN,lumber
3,AL_8_autauga_00008_L.jpg,4,Coleman Jas,500.0,NaN,1.0,NaN,225.0,100.0,NaN,lumber
4,AL_8_autauga_00009_L.jpg,1,Diranne & Son S,1500.0,NaN,5.0,NaN,350.0,1000.0,1875.0,lumber

In [103]:
for col in df6.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df6[col] = pd.to_numeric(df6[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df6 = df6[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [104]:
df6.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_barbour_00033_L.jpg,1,Moulthroup Robert,4500.0,NaN,16.0,NaN,3500.0,3375.0,NaN,construction
1,AL_8_barbour_00033_L.jpg,2,Keyhoe & Jay,1500.0,NaN,5.0,NaN,1355.0,1000.0,NaN,construction
2,AL_8_butler_00093_L.jpg,1,Steiner & Thomas,1000.0,NaN,12.0,NaN,2000.0,1200.0,4200.0,construction
3,AL_8_butler_00093_L.jpg,2,Wimberly & Perry,500.0,NaN,7.0,NaN,1000.0,200.0,2450.0,construction
4,AL_8_calhoun-benton_00118_L.jpg,1,Cook & Steward,2500.0,NaN,25.0,NaN,3750.0,3600.0,10000.0,construction

In [105]:
for col in df7.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df7[col] = pd.to_numeric(df7[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df7 = df7[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [106]:
df7.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_barbour_00038_L.jpg,1,Bruett & Fog,3000.0,NaN,4.0,NaN,320.0,32000.0,23872.0,food products
1,AL_8_barbour_00038_L.jpg,2,Bates & Marford,1500.0,NaN,3.0,NaN,400.0,4600.0,6300.0,food products
2,AL_8_barbour_00038_L.jpg,3,Thornton J M,2500.0,NaN,2.0,NaN,496.0,960.0,1276.0,food products
3,AL_8_barbour_00038_L.jpg,4,Blair C B,800.0,NaN,1.0,5.0,200.0,2260.0,3006.0,food products
4,AL_8_barbour_00038_L.jpg,5,McLeond & Bro,3000.0,NaN,1.0,4.0,200.0,745.0,1344.0,food products

In [107]:
for col in df8.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df8[col] = pd.to_numeric(df8[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_female', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df8 = df8[cols_to_keep]
print(ind_cols)

['ind_broadest']

In [108]:
df8.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_greene_00388_L.jpg,1,Smith James T.,NaN,NaN,NaN,NaN,NaN,2100150.0,NaN,food products
1,AL_8_greene_00388_L.jpg,2,Brown Thomas C,NaN,NaN,NaN,NaN,NaN,2100200.0,NaN,food products
2,AL_8_greene_00388_L.jpg,3,Brown James M,NaN,NaN,NaN,NaN,NaN,210018.0,NaN,food products
3,AL_8_greene_00388_L.jpg,4,Eatman David,NaN,NaN,NaN,NaN,NaN,210050.0,NaN,food products
4,AL_8_greene_00388_L.jpg,5,Hutson Uppenk,NaN,NaN,NaN,NaN,NaN,210050.0,NaN,food products

In [109]:
for col in df9.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df9[col] = pd.to_numeric(df9[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children',
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df9 = df9[cols_to_keep]

In [110]:
for col in df12.columns:
    if col.startswith("workers") or col == "materials_value" or col == "output" or col == "capital" or col == "total_wages":
        df12[col] = pd.to_numeric(df12[col], errors='coerce')

# First build a list of columns to keep:
base_keep = [
    'file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 
    'total_wages', 'materials_value', 'output'
]

ind_cols = ["ind_broadest"]

# Retain only these columns (if they exist in the dataframe)
cols_to_keep = base_keep + ind_cols
df12 = df12[cols_to_keep]

In [111]:
dataframe = [df1, df2, df3, df5, df6, df7]
df = pd.concat(dataframe, ignore_index=True)
df.head()

,file_name,firm_number,firm_name,capital,workers_adult_female,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_calhoun-benton_00114_L.jpg,1,Sinclair & Montgomery,3000.0,NaN,3.0,NaN,800.0,1800.0,4000.0,iron and steel products
1,AL_8_calhoun-benton_00115_L.jpg,1,Acker William,100.0,NaN,8.0,NaN,100.0,200.0,1000.0,iron and steel products
2,AL_8_calhoun-benton_00115_L.jpg,2,Paul Samuel,300.0,NaN,4.0,NaN,100.0,200.0,1000.0,iron and steel products
3,AL_8_calhoun-benton_00115_L.jpg,3,Martin Elijah,3500.0,NaN,7.0,NaN,130.0,130.0,500.0,iron and steel products
4,AL_8_calhoun-benton_00115_L.jpg,4,Martin William,350.0,NaN,7.0,NaN,150.0,130.0,500.0,iron and steel products

In [112]:
front_cols = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 
              'total_wages', 'materials_value', 'output']
remaining_cols = [col for col in df.columns if col not in front_cols]
df = df[front_cols + remaining_cols]

output_file = r"CMF_to_predict/1880_SS123567_to_predict.dta"
df.to_stata(output_file, write_index=False)

print("Data processing complete. Output saved to:", output_file)

Data processing complete. Output saved to: CMF_to_predict/1880_SS123567_to_predict.dta

In [113]:
# Read data
input_1880_SS123567 = pd.read_stata("CMF_to_predict/1880_SS123567_to_predict.dta")
# get the columns
input_1880_SS123567.columns

Index(['file_name', 'firm_number', 'firm_name', 'capital',
       'workers_adult_male', 'workers_adult_female', 'workers_children',
       'total_wages', 'materials_value', 'output', 'ind_broadest'],
      dtype='object')

In [114]:
def ratio(df, var1, var2):
    df[f'{var1}&{var2}'] = df[var1]/df[var2]

def ratio_tot_wages(df, var1, var2, var3, var4):
    df[f'{var1}&{var2}&{var3}&{var4}'] = (df[var1] + df[var2]+ df[var3])/df[var4]

In [115]:
ratio(input_1880_SS123567, 'materials_value', 'output')
ratio(input_1880_SS123567, 'materials_value', 'capital')
ratio(input_1880_SS123567, 'capital', 'output')
ratio(input_1880_SS123567, 'capital', 'materials_value')
ratio(input_1880_SS123567, 'output', 'materials_value')
ratio(input_1880_SS123567, 'output', 'capital')
ratio_tot_wages(input_1880_SS123567, 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages')
ratio(input_1880_SS123567, 'total_wages', 'output')

var_list = ["capital", "materials_value", "workers_adult_female", "workers_adult_male", "total_wages", "output", 'materials_value&output', 'materials_value&capital', 'capital&output', 'capital&materials_value', 'output&materials_value', 'output&capital','workers_adult_male&workers_adult_female&workers_children&total_wages', 'total_wages&output']

input_1880_SS123567.replace({np.inf: 0, -np.inf: 0, np.nan: 0}, inplace=True)

In [116]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import mahalanobis

industry_list = input_1880_SS123567["ind_broadest"].unique().tolist()
final_df = []

for industry in industry_list:
    input_df = input_1880_SS123567[input_1880_SS123567["ind_broadest"] == industry].copy()  # Ensure a copy

    if input_df.empty:
        continue  # Skip if there's no data for this industry

    # Compute mean and covariance matrix
    mean_vec = np.mean(input_df[var_list], axis=0)
    cov_matrix = np.cov(input_df[var_list], rowvar=False)

    # Check if covariance matrix is singular
    if np.linalg.det(cov_matrix) == 0:
        print(f"Skipping {industry}: Covariance matrix is singular")
        continue

    inv_cov_matrix = np.linalg.inv(cov_matrix)

    # Compute Mahalanobis distance for each firm
    distances = np.array([mahalanobis(row, mean_vec, inv_cov_matrix) for row in input_df[var_list].to_numpy()])
    
    # Compute contributions
    contributions = np.array([(row - mean_vec) * np.dot(inv_cov_matrix, (row - mean_vec)) for row in input_df[var_list].to_numpy()])
    contributions_df = pd.DataFrame(contributions, columns=[col + "_con" for col in var_list])

    # Identify the most anomalous variable for each row
    input_df['most_anomalous_var'] = contributions_df.idxmax(axis=1)
    input_df['mahalanobis'] = distances

    # Combine input_df with contributions_df (ensuring correct alignment)
    input_df = pd.concat([input_df.reset_index(drop=True), contributions_df.reset_index(drop=True)], axis=1)

    final_df.append(input_df)  # Append a COPY

# Combine all industry DataFrames into one
final_df = pd.concat(final_df, ignore_index=True)
print(industry_list)

['iron and steel products', 'paper and printing', 'clothing and textiles', 'lumber', 'construction', 'food products']

In [117]:
final_df['dist_squared'] = final_df['mahalanobis'] ** 2
for var in var_list:
    final_df[var + "_divided"] = final_df[var+"_con"]/final_df['dist_squared']
final_df['total'] = 0
for var in var_list:
    final_df['total'] = final_df['total'] + final_df[var + "_divided"]
final_df

,file_name,firm_number,firm_name,capital,workers_adult_male,workers_adult_female,workers_children,total_wages,materials_value,output,...,output_divided,materials_value&output_divided,materials_value&capital_divided,capital&output_divided,capital&materials_value_divided,output&materials_value_divided,output&capital_divided,workers_adult_male&workers_adult_female&workers_children&total_wages_divided,total_wages&output_divided,total
0,AL_8_calhoun-benton_00114_L.jpg,1,Sinclair & Montgomery,3000.0,3.0,0.0,0.0,800.0,1800.0,4000.0,...,0.055538,-0.027514,0.087704,0.179503,0.012641,0.016071,0.005849,0.006294,0.185771,1.0
1,AL_8_calhoun-benton_00115_L.jpg,1,Acker William,100.0,8.0,0.0,0.0,100.0,200.0,1000.0,...,0.202554,0.021653,0.097968,0.201126,-0.019482,0.011677,0.512208,0.002421,0.063039,1.0
2,AL_8_calhoun-benton_00115_L.jpg,2,Paul Samuel,300.0,4.0,0.0,0.0,100.0,200.0,1000.0,...,0.332094,-0.028850,0.041433,0.392238,-0.009051,0.008208,0.044220,0.004837,0.346472,1.0
3,AL_8_calhoun-benton_00115_L.jpg,3,Martin Elijah,3500.0,7.0,0.0,0.0,130.0,130.0,500.0,...,-0.027555,-0.000529,0.004635,0.968283,-0.003582,-0.000072,0.003279,0.000022,0.007555,1.0
4,AL_8_calhoun-benton_00115_L.jpg,4,Martin William,350.0,7.0,0.0,0.0,150.0,130.0,500.0,...,0.520075,-0.050262,0.168495,0.265374,0.003513,0.003043,-0.004997,0.008679,0.008855,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57948,dc_8_dist columbia_00064_r_L.jpg,5,Rinney W C and Son,30000.0,6.0,0.0,0.0,4000.0,170000.0,180000.0,...,0.504815,0.004518,-0.000466,0.010560,0.003309,0.004161,0.005711,-0.000003,0.001688,1.0
57949,dc_8_dist columbia_00065_r_L.jpg,1,White and Bro,600.0,1.0,0.0,0.0,300.0,6250.0,8250.0,...,0.172406,0.003160,0.000110,0.012438,-0.007113,0.000254,0.010485,0.000665,0.019431,1.0
57950,dc_8_dist columbia_00065_r_L.jpg,2,Harkon Wm,3000.0,1.0,0.0,0.0,1200.0,45150.0,50000.0,...,0.248759,0.029998,-0.000829,-0.052400,-0.001871,0.019150,-0.016290,0.000411,0.062310,1.0
57951,dc_8_dist columbia_00065_r_L.jpg,3,Port Charles,300.0,0.0,0.0,0.0,0.0,4175.0,5000.0,...,0.144453,-0.000898,0.000093,0.005559,-0.006803,-0.000381,0.016962,0.000428,0.045536,1.0
57952,dc_8_dist columbia_00065_r_L.jpg,4,Gaskin Charless,1500.0,2.0,0.0,0.0,1800.0,8575.0,11100.0,...,0.158907,0.006687,0.000224,0.023532,0.002082,0.001128,-0.011077,0.000705,0.026799,1.0

In [118]:
for var in var_list:
    batch = []
    for ind in industry_list:
        ind_specific = final_df[final_df["ind_broadest"] == ind].copy()  # Ensure a copy
        #ORIGINAL CUTOFF : .0001
        quantile_low = ind_specific[var + '_divided'].quantile(0.0001)
        quantile_high = ind_specific[var + '_divided'].quantile(1 - 0.0001)

        # Filter the lowest and highest 0.01% values
        lowest_values = ind_specific[ind_specific[var + '_divided'] <= quantile_low]
        highest_values = ind_specific[ind_specific[var + '_divided'] >= quantile_high]

        # Combine results
        result = pd.concat([lowest_values, highest_values])

        batch.append(result)

    batch = pd.concat(batch, ignore_index=True)

    if "materials_value&output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_materials_value'] = None
        variable_check['correct_output'] = None
        variable_check.to_csv(f"check/1880/SS123567/{var}_check_1880_SS_123567.csv", index=False)
    elif "output&materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_output'] = None
        variable_check['correct_materials_value'] = None
        variable_check.to_csv(f"check/1880/SS123567/{var}_check_1880_SS_123567.csv", index=False)

    elif "materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "materials_value" in left:
                variable_check['correct_materials_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_materials_value'] = None
        else:
            variable_check['correct_materials_value'] = None
        variable_check.to_csv(f"check/1880/SS123567/{var}_check_1880_SS_123567.csv", index=False)

    elif "output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "output" in left:
                variable_check['correct_output_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_output_value'] = None
        else:
            variable_check['correct_output_value'] = None
        variable_check.to_csv(f"check/1880/SS123567/{var}_check_1880_SS_123567.csv", index=False)

    else:
        parts = var.split("&")
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        if len(parts) == 2:
            left, right=parts
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{left}'] = None
            variable_check[f'correct_{right}'] = None
        else:
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{var}'] = None
        variable_check.to_csv(f"check/1880/SS123567/{var}_check_1880_SS_123567.csv", index=False)

/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/3423171729.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None

In [119]:
dataframe = [df9, df12]
df = pd.concat(dataframe, ignore_index=True)
df.head()

,file_name,firm_number,firm_name,capital,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest
0,AL_8_elmore_00336_L.jpg,1,Herren Daniel,3000.0,2.0,NaN,150.0,NaN,1063.0,food products
1,AL_8_elmore_00336_L.jpg,2,Herren Daniel,3000.0,2.0,NaN,150.0,NaN,1063.0,food products
2,AL_8_limestone_00534_L.jpg,1,Long Albert J,100.0,2.0,NaN,50.0,258.0,800.0,food products
3,AL_8_limestone_00534_L.jpg,2,Long Albert J,100.0,2.0,NaN,50.0,258.0,800.0,food products
4,AR_8_pulaski_00410_L.jpg,1,Wm Kisten,3000.0,6.0,NaN,2000.0,34325.0,49680.0,food products

In [120]:
front_cols = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 
              'total_wages', 'materials_value', 'output']
remaining_cols = [col for col in df.columns if col not in front_cols]
df = df[front_cols + remaining_cols]

output_file = r"CMF_to_predict/1880_SS912_to_predict.dta"
df.to_stata(output_file, write_index=False)

print("Data processing complete. Output saved to:", output_file)

Data processing complete. Output saved to: CMF_to_predict/1880_SS912_to_predict.dta

In [121]:
# Read data
input_1880_SS912 = pd.read_stata("CMF_to_predict/1880_SS912_to_predict.dta")
# get the columns
input_1880_SS912.columns

Index(['file_name', 'firm_number', 'firm_name', 'capital',
       'workers_adult_male', 'workers_children', 'total_wages',
       'materials_value', 'output', 'ind_broadest'],
      dtype='object')

In [122]:
def ratio(df, var1, var2):
    df[f'{var1}&{var2}'] = df[var1]/df[var2]

def ratio_tot_wages(df, var1, var2, var3):
    df[f'{var1}&{var2}&{var3}'] = (df[var1] + df[var2])/df[var3]

In [123]:
ratio(input_1880_SS912, 'materials_value', 'output')
ratio(input_1880_SS912, 'materials_value', 'capital')
ratio(input_1880_SS912, 'capital', 'output')
ratio(input_1880_SS912, 'capital', 'materials_value')
ratio(input_1880_SS912, 'output', 'materials_value')
ratio(input_1880_SS912, 'output', 'capital')
ratio_tot_wages(input_1880_SS912, 'workers_adult_male', 'workers_children', 'total_wages')
ratio(input_1880_SS912, 'total_wages', 'output')

var_list = ["capital", "materials_value", "workers_adult_male", "total_wages", "output", 'materials_value&output', 'materials_value&capital', 'capital&output', 'capital&materials_value', 'output&materials_value', 'output&capital','workers_adult_male&workers_children&total_wages', 'total_wages&output']

input_1880_SS912.replace({np.inf: 0, -np.inf: 0, np.nan: 0}, inplace=True)

In [124]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import mahalanobis

industry_list = input_1880_SS912["ind_broadest"].unique().tolist()
final_df = []

for industry in industry_list:
    input_df = input_1880_SS912[input_1880_SS912["ind_broadest"] == industry].copy()  # Ensure a copy

    if input_df.empty:
        continue  # Skip if there's no data for this industry

    # Compute mean and covariance matrix
    mean_vec = np.mean(input_df[var_list], axis=0)
    cov_matrix = np.cov(input_df[var_list], rowvar=False)

    # Check if covariance matrix is singular
    if np.linalg.det(cov_matrix) == 0:
        print(f"Skipping {industry}: Covariance matrix is singular")
        continue

    inv_cov_matrix = np.linalg.inv(cov_matrix)

    # Compute Mahalanobis distance for each firm
    distances = np.array([mahalanobis(row, mean_vec, inv_cov_matrix) for row in input_df[var_list].to_numpy()])
    
    # Compute contributions
    contributions = np.array([(row - mean_vec) * np.dot(inv_cov_matrix, (row - mean_vec)) for row in input_df[var_list].to_numpy()])
    contributions_df = pd.DataFrame(contributions, columns=[col + "_con" for col in var_list])

    # Identify the most anomalous variable for each row
    input_df['most_anomalous_var'] = contributions_df.idxmax(axis=1)
    input_df['mahalanobis'] = distances

    # Combine input_df with contributions_df (ensuring correct alignment)
    input_df = pd.concat([input_df.reset_index(drop=True), contributions_df.reset_index(drop=True)], axis=1)

    final_df.append(input_df)  # Append a COPY

# Combine all industry DataFrames into one
final_df = pd.concat(final_df, ignore_index=True)
print(industry_list)

['food products', 'not mfg']

In [125]:
final_df['dist_squared'] = final_df['mahalanobis'] ** 2
for var in var_list:
    final_df[var + "_divided"] = final_df[var+"_con"]/final_df['dist_squared']
final_df['total'] = 0
for var in var_list:
    final_df['total'] = final_df['total'] + final_df[var + "_divided"]
final_df

,file_name,firm_number,firm_name,capital,workers_adult_male,workers_children,total_wages,materials_value,output,ind_broadest,...,output_divided,materials_value&output_divided,materials_value&capital_divided,capital&output_divided,capital&materials_value_divided,output&materials_value_divided,output&capital_divided,workers_adult_male&workers_children&total_wages_divided,total_wages&output_divided,total
0,AL_8_elmore_00336_L.jpg,1,Herren Daniel,3000.0,2.0,0.0,150.0,0.0,1063.0,food products,...,0.054482,-0.035111,0.051291,1.109702,0.004615,0.005588,0.022306,0.001800,-0.212560,1.0
1,AL_8_elmore_00336_L.jpg,2,Herren Daniel,3000.0,2.0,0.0,150.0,0.0,1063.0,food products,...,0.054482,-0.035111,0.051291,1.109702,0.004615,0.005588,0.022306,0.001800,-0.212560,1.0
2,AL_8_limestone_00534_L.jpg,1,Long Albert J,100.0,2.0,0.0,50.0,258.0,800.0,food products,...,0.184631,0.024651,0.183333,0.112720,0.019136,0.017398,0.009178,0.012049,-0.084065,1.0
3,AL_8_limestone_00534_L.jpg,2,Long Albert J,100.0,2.0,0.0,50.0,258.0,800.0,food products,...,0.184631,0.024651,0.183333,0.112720,0.019136,0.017398,0.009178,0.012049,-0.084065,1.0
4,AR_8_pulaski_00410_L.jpg,1,Wm Kisten,3000.0,6.0,0.0,2000.0,34325.0,49680.0,food products,...,0.015700,-0.003772,0.018295,-0.005185,0.032104,0.035325,0.011293,0.017021,0.043853,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6082,WV_8_greenbrier_00133_L.jpg,2,Mann Matthew,950.0,14.0,1.0,3600.0,0.0,5400.0,not mfg,...,-0.070937,-0.005769,0.031242,0.008349,0.046768,0.096072,0.012304,0.613837,0.010287,1.0
6083,WV_8_jefferson_00256_L.jpg,1,Strider Samul T.,600.0,4.0,0.0,600.0,40.0,600.0,not mfg,...,0.575739,-0.006847,0.038640,0.013377,0.004204,-0.005861,0.094799,0.088379,0.011308,1.0
6084,WV_8_jefferson_00256_L.jpg,2,James Flangam Heirs,1800.0,15.0,0.0,1200.0,120.0,7500.0,not mfg,...,0.078243,-0.006866,0.007270,0.010245,0.028614,0.640242,0.002873,0.096041,0.014414,1.0
6085,WV_8_jefferson_00257_L.jpg,1,Knoll Bi?,8000.0,10.0,0.0,1500.0,0.0,12000.0,not mfg,...,-0.334339,-0.004570,-0.019256,0.005211,0.023489,0.126196,0.077432,0.045459,0.004927,1.0
6086,WV_8_preston_00546_L.jpg,1,Sullivan J Pest,500.0,10.0,0.0,3500.0,100.0,1350.0,not mfg,...,1.579287,-0.010427,0.019031,0.022747,0.104520,-0.020042,0.030219,0.166936,0.022073,1.0

In [126]:
for var in var_list:
    batch = []
    for ind in industry_list:
        ind_specific = final_df[final_df["ind_broadest"] == ind].copy()  # Ensure a copy
        #ORIGINAL CUTOFF : .0001
        quantile_low = ind_specific[var + '_divided'].quantile(0.0001)
        quantile_high = ind_specific[var + '_divided'].quantile(1 - 0.0001)

        # Filter the lowest and highest 0.01% values
        lowest_values = ind_specific[ind_specific[var + '_divided'] <= quantile_low]
        highest_values = ind_specific[ind_specific[var + '_divided'] >= quantile_high]

        # Combine results
        result = pd.concat([lowest_values, highest_values])

        batch.append(result)

    batch = pd.concat(batch, ignore_index=True)

    if "materials_value&output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_materials_value'] = None
        variable_check['correct_output'] = None
        variable_check.to_csv(f"check/1880/SS912/{var}_check_1880_SS_912.csv", index=False)
    elif "output&materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_output'] = None
        variable_check['correct_materials_value'] = None
        variable_check.to_csv(f"check/1880/SS912/{var}_check_1880_SS_912.csv", index=False)

    elif "materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "materials_value" in left:
                variable_check['correct_materials_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_materials_value'] = None
        else:
            variable_check['correct_materials_value'] = None
        variable_check.to_csv(f"check/1880/SS912/{var}_check_1880_SS_912.csv", index=False)

    elif "output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "output" in left:
                variable_check['correct_output_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_output_value'] = None
        else:
            variable_check['correct_output_value'] = None
        variable_check.to_csv(f"check/1880/SS912/{var}_check_1880_SS_912.csv", index=False)

    else:
        parts = var.split("&")
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        if len(parts) == 2:
            left, right=parts
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{left}'] = None
            variable_check[f'correct_{right}'] = None
        else:
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{var}'] = None
        variable_check.to_csv(f"check/1880/SS912/{var}_check_1880_SS_912.csv", index=False)

/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_materials_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:80: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1355322691.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_output_value'] = None

In [127]:
front_cols = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 
              'total_wages', 'materials_value', 'output']
remaining_cols = [col for col in df4.columns if col not in front_cols]
df4 = df4[front_cols + remaining_cols]

output_file = r"CMF_to_predict/1880_SS4_to_predict.dta"
df4.to_stata(output_file, write_index=False)

print("Data processing complete. Output saved to:", output_file)

Data processing complete. Output saved to: CMF_to_predict/1880_SS4_to_predict.dta

In [128]:
# Read data
input_1880_SS4 = pd.read_stata("CMF_to_predict/1880_SS4_to_predict.dta")
# get the columns
input_1880_SS4.columns

Index(['file_name', 'firm_number', 'firm_name', 'capital',
       'workers_adult_male', 'workers_adult_female', 'workers_children',
       'total_wages', 'materials_value', 'output', 'ind_broadest'],
      dtype='object')

In [129]:
def ratio(df, var1, var2):
    df[f'{var1}&{var2}'] = df[var1]/df[var2]

def ratio_tot_wages(df, var1, var2, var3, var4):
    df[f'{var1}&{var2}&{var3}&{var4}'] = (df[var1] + df[var2]+ df[var3])/df[var4]

In [130]:
ratio(input_1880_SS4, 'materials_value', 'output')
ratio(input_1880_SS4, 'materials_value', 'capital')
ratio(input_1880_SS4, 'capital', 'output')
ratio(input_1880_SS4, 'capital', 'materials_value')
ratio(input_1880_SS4, 'output', 'materials_value')
ratio(input_1880_SS4, 'output', 'capital')
ratio_tot_wages(input_1880_SS4, 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages')
ratio(input_1880_SS4, 'total_wages', 'output')

var_list = ["capital", "materials_value", "workers_adult_female", "workers_adult_male", "total_wages", "output", 'materials_value&output', 'materials_value&capital', 'capital&output', 'capital&materials_value', 'output&materials_value', 'output&capital','workers_adult_male&workers_adult_female&workers_children&total_wages', 'total_wages&output']

input_1880_SS4.replace({np.inf: 0, -np.inf: 0, np.nan: 0}, inplace=True)

In [131]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import mahalanobis

industry_list = input_1880_SS4["ind_broadest"].unique().tolist()
final_df = []

for industry in industry_list:
    input_df = input_1880_SS4[input_1880_SS4["ind_broadest"] == industry].copy()  # Ensure a copy

    if input_df.empty:
        continue  # Skip if there's no data for this industry

    # Compute mean and covariance matrix
    mean_vec = np.mean(input_df[var_list], axis=0)
    cov_matrix = np.cov(input_df[var_list], rowvar=False)

    # Check if covariance matrix is singular
    if np.linalg.det(cov_matrix) == 0:
        print(f"Skipping {industry}: Covariance matrix is singular")
        continue

    inv_cov_matrix = np.linalg.inv(cov_matrix)

    # Compute Mahalanobis distance for each firm
    distances = np.array([mahalanobis(row, mean_vec, inv_cov_matrix) for row in input_df[var_list].to_numpy()])
    
    # Compute contributions
    contributions = np.array([(row - mean_vec) * np.dot(inv_cov_matrix, (row - mean_vec)) for row in input_df[var_list].to_numpy()])
    contributions_df = pd.DataFrame(contributions, columns=[col + "_con" for col in var_list])

    # Identify the most anomalous variable for each row
    input_df['most_anomalous_var'] = contributions_df.idxmax(axis=1)
    input_df['mahalanobis'] = distances

    # Combine input_df with contributions_df (ensuring correct alignment)
    input_df = pd.concat([input_df.reset_index(drop=True), contributions_df.reset_index(drop=True)], axis=1)

    final_df.append(input_df)  # Append a COPY

# Combine all industry DataFrames into one
final_df = pd.concat(final_df, ignore_index=True)
print(industry_list)

['leather products']

In [132]:
final_df['dist_squared'] = final_df['mahalanobis'] ** 2
for var in var_list:
    final_df[var + "_divided"] = final_df[var+"_con"]/final_df['dist_squared']
final_df['total'] = 0
for var in var_list:
    final_df['total'] = final_df['total'] + final_df[var + "_divided"]
final_df

,file_name,firm_number,firm_name,capital,workers_adult_male,workers_adult_female,workers_children,total_wages,materials_value,output,...,output_divided,materials_value&output_divided,materials_value&capital_divided,capital&output_divided,capital&materials_value_divided,output&materials_value_divided,output&capital_divided,workers_adult_male&workers_adult_female&workers_children&total_wages_divided,total_wages&output_divided,total
0,AL_8_barbour_00652_L.jpg,1,Stow & Hickey,8000.0,7.0,0.0,0.0,1200.0,60003120.0,80001000.0,...,-0.078415,0.001446,0.111760,-0.033859,0.054876,0.015437,0.081817,0.004228,0.030607,1.0
1,AL_8_barbour_00653_L.jpg,1,Prier HWB & Co,1500.0,2.0,0.0,1.0,400.0,10001850.0,18003125.0,...,-0.071994,0.000912,0.054021,-0.014946,0.029194,0.010103,0.047684,0.002736,0.014960,1.0
2,AL_8_bibb_00047_L.jpg,1,Davis J Madison,500.0,2.0,0.0,0.0,400.0,5001040.0,15001750.0,...,-0.067151,0.000830,0.053281,-0.013716,0.026914,0.010749,0.034111,0.002621,0.013938,1.0
3,AL_8_blount_00052_L.jpg,1,Kael & Wods,1500.0,2.0,0.0,0.0,250.0,900535.0,8400900.0,...,-0.071839,0.000524,0.062958,-0.014171,0.028226,0.009805,0.046386,0.002653,0.014273,1.0
4,AL_8_blount_00053_L.jpg,1,Daniel W Durban,1000.0,2.0,0.0,0.0,500.0,5001125.0,20001500.0,...,-0.067465,0.000555,0.065850,-0.014566,0.028205,0.010874,0.038837,0.002713,0.014689,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3080,WV_8_upshur_00683_L.jpg,1,M.C Rohoboyh,4500.0,2.0,0.0,0.0,350.0,15002150.0,30003000.0,...,-0.080871,0.000874,0.056274,-0.018420,0.036087,0.011053,0.052085,0.003042,0.017767,1.0
3081,WV_8_upshur_00683_L.jpg,2,M.L. Rohrbough,4500.0,2.0,0.0,0.0,350.0,15002150.0,30003000.0,...,-0.080871,0.000874,0.056274,-0.018420,0.036087,0.011053,0.052085,0.003042,0.017767,1.0
3082,WV_8_wayne_00692_L.jpg,1,Fras Leo Johored,1000.0,1.0,0.0,0.0,200.0,250350.0,750525.0,...,-0.070354,0.000535,0.054594,-0.012318,0.025883,0.008983,0.046594,0.002518,0.012740,1.0
3083,WV_8_wayne_00692_L.jpg,2,Thrasher John L,1000.0,1.0,0.0,0.0,200.0,250350.0,750525.0,...,-0.070354,0.000535,0.054594,-0.012318,0.025883,0.008983,0.046594,0.002518,0.012740,1.0
3084,dc_8_dist columbia_00063_r_L.jpg,1,W.R. Turner,10000.0,3.0,0.0,0.0,425.0,3265645.0,42844894.0,...,-0.085979,0.000816,0.057832,-0.024383,0.046914,0.012251,0.052978,0.003399,0.022320,1.0

In [133]:
for var in var_list:
    batch = []
    for ind in industry_list:
        ind_specific = final_df[final_df["ind_broadest"] == ind].copy()  # Ensure a copy
        #ORIGINAL CUTOFF : .0001
        quantile_low = ind_specific[var + '_divided'].quantile(0.0001)
        quantile_high = ind_specific[var + '_divided'].quantile(1 - 0.0001)

        # Filter the lowest and highest 0.01% values
        lowest_values = ind_specific[ind_specific[var + '_divided'] <= quantile_low]
        highest_values = ind_specific[ind_specific[var + '_divided'] >= quantile_high]

        # Combine results
        result = pd.concat([lowest_values, highest_values])

        batch.append(result)

    batch = pd.concat(batch, ignore_index=True)

    if "materials_value&output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_tanning_mat_total_value'] = None
        variable_check['correct_currying_mat_total_value'] = None
        variable_check['correct_tanning_prod_total_value'] = None
        variable_check['correct_currying_prod_total_value'] = None
        variable_check.to_csv(f"check/1880/SS4/{var}_check_1880_SS_4.csv", index=False)
    elif "output&materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_tanning_prod_total_value'] = None
        variable_check['correct_currying_prod_total_value'] = None
        variable_check['correct_tanning_mat_total_value'] = None
        variable_check['correct_currying_mat_total_value'] = None
        variable_check.to_csv(f"check/1880/SS4/{var}_check_1880_SS_4.csv", index=False)

    elif "materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "materials_value" in left:
                variable_check['correct_tanning_mat_total_value'] = None
                variable_check['correct_currying_mat_total_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_tanning_mat_total_value'] = None
                variable_check['correct_currying_mat_total_value'] = None
        else:
            variable_check['correct_tanning_mat_total_value'] = None
            variable_check['correct_currying_mat_total_value'] = None
        variable_check.to_csv(f"check/1880/SS4/{var}_check_1880_SS_4.csv", index=False)

    elif "output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "output" in left:
                variable_check['correct_tanning_prod_total_value'] = None
                variable_check['correct_currying_prod_total_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_tanning_prod_total_value'] = None
                variable_check['correct_currying_prod_total_value'] = None
        else:
            variable_check['correct_tanning_prod_total_value'] = None
            variable_check['correct_currying_prod_total_value'] = None
        variable_check.to_csv(f"check/1880/SS4/{var}_check_1880_SS_4.csv", index=False)

    else:
        parts = var.split("&")
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        if len(parts) == 2:
            left, right=parts
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{left}'] = None
            variable_check[f'correctS_{right}'] = None
        else:
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{var}'] = None
        variable_check.to_csv(f"check/1880/SS4/{var}_check_1880_SS_4.csv", index=False)

/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_mat_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:89: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_tanning_prod_total_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/4120986330.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_currying_prod_total_value'] = None

In [134]:
front_cols = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 
              'total_wages', 'materials_value', 'output']
remaining_cols = [col for col in df8.columns if col not in front_cols]
df8 = df8[front_cols + remaining_cols]

output_file = r"CMF_to_predict/1880_SS8_to_predict.dta"
df8.to_stata(output_file, write_index=False)

print("Data processing complete. Output saved to:", output_file)

Data processing complete. Output saved to: CMF_to_predict/1880_SS8_to_predict.dta

In [135]:
# Read data
input_1880_SS8 = pd.read_stata("CMF_to_predict/1880_SS8_to_predict.dta")
# get the columns
input_1880_SS8.columns

Index(['file_name', 'firm_number', 'firm_name', 'capital',
       'workers_adult_male', 'workers_adult_female', 'workers_children',
       'total_wages', 'materials_value', 'output', 'ind_broadest'],
      dtype='object')

In [136]:
def ratio(df, var1, var2):
    df[f'{var1}&{var2}'] = df[var1]/df[var2]

def ratio_tot_wages(df, var1, var2, var3, var4):
    df[f'{var1}&{var2}&{var3}&{var4}'] = (df[var1] + df[var2]+ df[var3])/df[var4]

In [137]:
ratio(input_1880_SS8, 'materials_value', 'output')
ratio(input_1880_SS8, 'materials_value', 'capital')
ratio(input_1880_SS8, 'capital', 'output')
ratio(input_1880_SS8, 'capital', 'materials_value')
ratio(input_1880_SS8, 'output', 'materials_value')
ratio(input_1880_SS8, 'output', 'capital')
ratio_tot_wages(input_1880_SS8, 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages')
ratio(input_1880_SS8, 'total_wages', 'output')

var_list = ["capital", "materials_value", "workers_adult_female", "workers_adult_male", "total_wages", "output", 'materials_value&output', 'materials_value&capital', 'capital&output', 'capital&materials_value', 'output&materials_value', 'output&capital','workers_adult_male&workers_adult_female&workers_children&total_wages', 'total_wages&output']

input_1880_SS8.replace({np.inf: 0, -np.inf: 0, np.nan: 0}, inplace=True)

In [138]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import mahalanobis

industry_list = input_1880_SS8["ind_broadest"].unique().tolist()
final_df = []

for industry in industry_list:
    input_df = input_1880_SS8[input_1880_SS8["ind_broadest"] == industry].copy()  # Ensure a copy

    if input_df.empty:
        continue  # Skip if there's no data for this industry

    # Compute mean and covariance matrix
    mean_vec = np.mean(input_df[var_list], axis=0)
    cov_matrix = np.cov(input_df[var_list], rowvar=False)

    # Check if covariance matrix is singular
    if np.linalg.det(cov_matrix) == 0:
        print(f"Skipping {industry}: Covariance matrix is singular")
        continue

    inv_cov_matrix = np.linalg.inv(cov_matrix)

    # Compute Mahalanobis distance for each firm
    distances = np.array([mahalanobis(row, mean_vec, inv_cov_matrix) for row in input_df[var_list].to_numpy()])
    
    # Compute contributions
    contributions = np.array([(row - mean_vec) * np.dot(inv_cov_matrix, (row - mean_vec)) for row in input_df[var_list].to_numpy()])
    contributions_df = pd.DataFrame(contributions, columns=[col + "_con" for col in var_list])

    # Identify the most anomalous variable for each row
    input_df['most_anomalous_var'] = contributions_df.idxmax(axis=1)
    input_df['mahalanobis'] = distances

    # Combine input_df with contributions_df (ensuring correct alignment)
    input_df = pd.concat([input_df.reset_index(drop=True), contributions_df.reset_index(drop=True)], axis=1)

    final_df.append(input_df)  # Append a COPY

# Combine all industry DataFrames into one
final_df = pd.concat(final_df, ignore_index=True)
print(industry_list)

['food products']

In [139]:
final_df['dist_squared'] = final_df['mahalanobis'] ** 2
for var in var_list:
    final_df[var + "_divided"] = final_df[var+"_con"]/final_df['dist_squared']
final_df['total'] = 0
for var in var_list:
    final_df['total'] = final_df['total'] + final_df[var + "_divided"]
final_df

,file_name,firm_number,firm_name,capital,workers_adult_male,workers_adult_female,workers_children,total_wages,materials_value,output,...,output_divided,materials_value&output_divided,materials_value&capital_divided,capital&output_divided,capital&materials_value_divided,output&materials_value_divided,output&capital_divided,workers_adult_male&workers_adult_female&workers_children&total_wages_divided,total_wages&output_divided,total
0,AL_8_greene_00388_L.jpg,1,Smith James T.,0.0,0.0,0.0,0.0,0.0,2100150.00,0.0,...,-0.006290,0.000467,0.001827,-0.003267,-0.016614,0.001965,0.005204,0.000394,0.005517,1.0
1,AL_8_greene_00388_L.jpg,2,Brown Thomas C,0.0,0.0,0.0,0.0,0.0,2100200.00,0.0,...,-0.006290,0.000467,0.001827,-0.003267,-0.016614,0.001965,0.005204,0.000394,0.005517,1.0
2,AL_8_greene_00388_L.jpg,3,Brown James M,0.0,0.0,0.0,0.0,0.0,210018.00,0.0,...,-0.006290,0.000465,0.001825,-0.003267,-0.016614,0.001965,0.005204,0.000394,0.005517,1.0
3,AL_8_greene_00388_L.jpg,4,Eatman David,0.0,0.0,0.0,0.0,0.0,210050.00,0.0,...,-0.006290,0.000465,0.001825,-0.003267,-0.016614,0.001965,0.005204,0.000394,0.005517,1.0
4,AL_8_greene_00388_L.jpg,5,Hutson Uppenk,0.0,0.0,0.0,0.0,0.0,210050.00,0.0,...,-0.006290,0.000465,0.001825,-0.003267,-0.016614,0.001965,0.005204,0.000394,0.005517,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3532,WI_8_la crosse_00255_L.jpg,1,Burnes Cheese F Arolle,1200.0,1.0,0.0,0.0,191.0,501.53,0.0,...,-0.001645,0.001466,0.004321,0.000125,-0.021420,-0.004823,0.009852,0.000758,0.013260,1.0
3533,WI_8_la crosse_00263_L.jpg,1,Barcley James,1600.0,0.0,0.0,0.0,0.0,501.53,0.0,...,-0.004572,0.000441,0.001934,-0.001366,-0.002507,0.000682,0.005319,0.000448,0.005809,1.0
3534,WI_8_la crosse_00265_L.jpg,1,Gray & VanWaters,300.0,0.0,0.0,0.0,0.0,0.00,0.0,...,-0.006073,0.000467,0.001866,-0.002981,-0.014386,0.001768,0.005288,0.000408,0.005637,1.0
3535,WV_8_harrison_00196_L.jpg,1,John B. Watkins,500.0,1.0,0.0,0.0,100.0,0.00,0.0,...,-0.003504,0.001378,0.003926,-0.001702,-0.034675,-0.002926,0.009083,0.000701,0.011256,1.0
3536,dc_8_dist columbia_00038_r_L.jpg,1,Ward Frank K,10000.0,8.0,0.0,0.0,3300.0,0.00,0.0,...,0.002284,0.000054,-0.000027,0.001260,0.003693,-0.001651,-0.000454,-0.000054,0.000354,1.0

In [140]:
for var in var_list:
    batch = []
    for ind in industry_list:
        ind_specific = final_df[final_df["ind_broadest"] == ind].copy()  # Ensure a copy
        #ORIGINAL CUTOFF : .0001
        quantile_low = ind_specific[var + '_divided'].quantile(0.0001)
        quantile_high = ind_specific[var + '_divided'].quantile(1 - 0.0001)

        # Filter the lowest and highest 0.01% values
        lowest_values = ind_specific[ind_specific[var + '_divided'] <= quantile_low]
        highest_values = ind_specific[ind_specific[var + '_divided'] >= quantile_high]

        # Combine results
        result = pd.concat([lowest_values, highest_values])

        batch.append(result)

    batch = pd.concat(batch, ignore_index=True)

    if "materials_value&output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_milk_cost'] = None
        variable_check['correct_cheese_cost'] = None
        variable_check['correct_cheese_furnish_cost'] = None
        variable_check['correct_butter_cost'] = None
        variable_check['correct_butter_furnish_cost'] = None
        variable_check['correct_butter_buttermilk_skim_value'] = None
        variable_check['correct_condensed_milk_value'] = None
        variable_check.to_csv(f"check/1880/SS8/{var}_check_1880_SS_8.csv", index=False)
    elif "output&materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        variable_check['correct_butter_buttermilk_skim_value'] = None
        variable_check['correct_condensed_milk_value'] = None
        variable_check['correct_milk_cost'] = None
        variable_check['correct_cheese_cost'] = None
        variable_check['correct_cheese_furnish_cost'] = None
        variable_check['correct_butter_cost'] = None
        variable_check['correct_butter_furnish_cost'] = None
        variable_check.to_csv(f"check/1880/SS8/{var}_check_1880_SS_8.csv", index=False)

    elif "materials_value" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "materials_value" in left:
                variable_check['correct_milk_cost'] = None
                variable_check['correct_cheese_cost'] = None
                variable_check['correct_cheese_furnish_cost'] = None
                variable_check['correct_butter_cost'] = None
                variable_check['correct_butter_furnish_cost'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_milk_cost'] = None
                variable_check['correct_cheese_cost'] = None
                variable_check['correct_cheese_furnish_cost'] = None
                variable_check['correct_butter_cost'] = None
                variable_check['correct_butter_furnish_cost'] = None
        else:
            variable_check['correct_milk_cost'] = None
            variable_check['correct_cheese_cost'] = None
            variable_check['correct_cheese_furnish_cost'] = None
            variable_check['correct_butter_cost'] = None
            variable_check['correct_butter_furnish_cost'] = None
        variable_check.to_csv(f"check/1880/SS8/{var}_check_1880_SS_8.csv", index=False)

    elif "output" in var:
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        variable_check['transcription_error'] =  None
        parts = var.split("&")
        if len(parts) == 2:
            left, right=parts
            if "output" in left:
                variable_check['correct_butter_buttermilk_skim_value'] = None
                variable_check['correct_condensed_milk_value'] = None
                variable_check[f'correct_{right}'] = None
            else:
                variable_check[f'correct_{left}'] = None
                variable_check['correct_butter_buttermilk_skim_value'] = None
                variable_check['correct_condensed_milk_value'] = None
        else:
            variable_check['correct_butter_buttermilk_skim_value'] = None
            variable_check['correct_condensed_milk_value'] = None
        variable_check.to_csv(f"check/1880/SS8/{var}_check_1880_SS_8.csv", index=False)

    else:
        parts = var.split("&")
        output_var_list = ['file_name', 'firm_number', 'firm_name', 'capital', 'workers_adult_male', 'workers_adult_female', 'workers_children', 'total_wages', 'materials_value', 'output']
        variable_check = batch[output_var_list]
        if len(parts) == 2:
            left, right=parts
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{left}'] = None
            variable_check[f'correct_{right}'] = None
        else:
            variable_check['transcription_error'] =  None
            variable_check[f'correct_{var}'] = None
        variable_check.to_csv(f"check/1880/SS8/{var}_check_1880_SS_8.csv", index=False)

/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_milk_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{var}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_buttermilk_skim_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_condensed_milk_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_milk_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_buttermilk_skim_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_condensed_milk_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_milk_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:58: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{right}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:86: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_buttermilk_skim_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_condensed_milk_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check[f'correct_{left}'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_milk_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_cheese_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_furnish_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['transcription_error'] =  None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_butter_buttermilk_skim_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_condensed_milk_value'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  variable_check['correct_milk_cost'] = None
/var/folders/9v/swhhkcgn3h543bcvl6qz76lc0000gn/T/ipykernel_15188/1369393542.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
